/** Stable built-in entity taxonomy initialized for every new world. */
export const DEFAULT_ENTITY_TYPES = [
  ['core_character', 'Character'],
  ['core_place', 'Place'],
  ['core_faction', 'Faction'],
  ['core_event', 'Event'],
  ['core_world', 'World'],
  ['core_planet', 'Planet'],
  ['core_continent', 'Continent'],
  ['core_ocean', 'Ocean'],
  ['core_region', 'Region'],
  ['core_country', 'Country'],
  ['core_province', 'Province'],
  ['core_city', 'City'],
  ['core_district', 'District'],
  ['core_location', 'Location'],
  ['core_landmark', 'Landmark'],
  ['core_river', 'River'],
  ['core_mountain', 'Mountain'],
  ['core_sea', 'Sea'],
  ['core_family', 'Family'],
  ['core_dynasty', 'Dynasty'],
  ['core_occupation', 'Occupation'],
  ['core_title', 'Title'],
  ['core_culture', 'Culture'],
  ['core_organization', 'Organization'],
  ['core_government', 'Government'],
  ['core_army', 'Army'],
  ['core_company', 'Company'],
  ['core_guild', 'Guild'],
  ['core_school', 'School'],
  ['core_religion', 'Religion'],
  ['core_ethnicity', 'Ethnicity'],
  ['core_institution', 'Institution'],
  ['core_law', 'Law'],
  ['core_species', 'Species'],
  ['core_race', 'Race'],
  ['core_creature', 'Creature'],
  ['core_plant', 'Plant'],
  ['core_disease', 'Disease'],
  ['core_technology', 'Technology'],
  ['core_magic_system', 'Magic System'],
  ['core_economy', 'Economy'],
  ['core_political_system', 'Political System'],
  ['core_economic_system', 'Economic System'],
  ['core_language', 'Language'],
  ['core_calendar', 'Calendar'],
  ['core_item', 'Item'],
  ['core_resource', 'Resource'],
  ['core_concept', 'Concept'],
  ['core_plot_thread', 'Plot Thread'],
] as const;
